name: Trelnex.Core.Api Workflow

on:
  pull_request:
    paths:
      - .github/workflows/nuget.yml
      - .github/workflows/ci-cd-core-api.yml
      - Trelnex.Core.Api/**
  push:
    branches: [ main ]
    paths:
      - .github/workflows/nuget.yml
      - .github/workflows/ci-cd-core-api.yml
      - Trelnex.Core.Api/**
  workflow_dispatch:

jobs:

  # ---------------------------------------------------------------------
  # 1. Test
  # ---------------------------------------------------------------------
  test:
    name: Trelnex.Core.Api.Tests
    uses: ./.github/workflows/test.yml

    with:
      dotnet_version: '9.0.x'
      project_name: 'Trelnex.Core.Api.Tests'

  # ---------------------------------------------------------------------
  # 2. Restore, Build, Tag, Pack and Push
  # ---------------------------------------------------------------------
  build:
    uses: ./.github/workflows/nuget.yml

    needs:
      - test

    with:
      dotnet_version: '9.0.x'
      project_name: 'Trelnex.Core.Api'
      tag_prefix: 'trelnex-core-api-'

    secrets: inherit
