name: Default NuGet Workflow

on:
  workflow_call:
    inputs:
      dotnet_version:
        description: 'The version of the .NET SDK; e.g. 9.0.x'
        required: true
        type: string
      project_name:
        description: 'The project name; e.g. Trelnex.Core'
        required: true
        type: string
      tag_prefix:
        description: 'A prefix to the tag name; e.g. trelnex-core-'
        required: true
        type: string

jobs:

  # ---------------------------------------------------------------------
  # 1. Restore, Build, Tag, Pack and Push
  # ---------------------------------------------------------------------
  build:

    name: Restore, Build, Tag, Pack and Push
    runs-on: [ ubuntu-latest ]

    steps:

      - name: checkout
        uses: actions/checkout@v4
        with:
          # disable shallow clone
          fetch-depth: 0

      - name: dotnet nuget add source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name "github" "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: dotnet restore
        run: dotnet restore ${{ inputs.project_name }}/${{ inputs.project_name }}.csproj

      - name: dotnet build
        run: dotnet build ${{ inputs.project_name }}/${{ inputs.project_name }}.csproj --no-restore

      - name: bump version and push tag
        if: (github.ref == 'refs/heads/main')
        id: tag_version
        uses: StevenKehrli/Trelnex.MonoTag@1.0.0
        with:
          project_path: ${{ inputs.project_name }}
          tag_prefix: ${{ inputs.tag_prefix }}

      - name: dotnet pack
        if: (github.ref == 'refs/heads/main')
        run: dotnet pack ${{ inputs.project_name }}/${{ inputs.project_name }}.csproj --no-restore -p:PackageVersion=${{ steps.tag_version.outputs.new_semver }}

      - name: dotnet nuget push
        if: (github.ref == 'refs/heads/main')
        run: dotnet nuget push "${{ inputs.project_name }}/bin/Release/${{ inputs.project_name }}.${{ steps.tag_version.outputs.new_semver }}.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
